#!/bin/bash

#SBATCH -N 1 # node count
#SBATCH -c 16
#SBATCH -t 72:00:00
#SBATCH --mem-per-cpu=2000
# sends mail when process begins and when it ends
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --mail-user=[user email]

# set the number of threads to be used for this run
export OMP_NUM_THREADS=16

./step5_ncRNA.sh
