#!/bin/bash

#SBATCH -N 1 # node count
#SBATCH -c 16
#SBATCH -t 72:00:00
# sends mail when process begins and when it ends
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --mail-user=[user email]

cd [path to working directory]

# set the number of threads to be used for this run
export OMP_NUM_THREADS=16

./step5_cRNA_eff.sh
