#!/bin/bash

#SBATCH -N 1 # node count
#SBATCH --ntasks-per-node=16
#SBATCH -t 24:00:00
# sends mail when process begins and when it ends
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --mail-user=[user email]

# set the number of threads to be used for this run
export OMP_NUM_THREADS=16

cd [path to working directory]

./step2_ncRNA.sh reads_ncRNA.fasta
